import argparse
import numpy as np
import tifffile
import sys
import os
from ANUNetCDF import *

def convert_anunc_to_tiff(input_path, output_path):
    """Loads a tomo*.nc file and saves it as a 3D TIFF stack."""
    try:
        # Load the numpy array from the ANUY netcdf format

        anunc = ANUNetCDF()
        data = anunc.readFile(fn=input_path, imagetype=ANUNetCDFType.Tomo)[0]
        
        if data.ndim != 3:
            print(f"Error: Input array must be 3D. Found shape {data.shape}")
            sys.exit(1)
            
        # Save using tifffile
        # imagej=True ensures compatibility with scientific viewers
        tifffile.imwrite(output_path, data, imagej=True)
        print(f"Success: Saved {input_path} to {output_path} (Shape: {data.shape})")

    except FileNotFoundError:
        print(f"Error: The file '{input_path}' was not found.")
    except Exception as e:
        print(f"An unexpected error occurred: {e}")

def main():
    parser = argparse.ArgumentParser(
        description="Convert a 3D mango tomo image (.nc) to a 3D TIFF stack."
    )
    
    # Positional Arguments
    parser.add_argument("input", help="Path to the source tomo .nc file, generated by mango")
    parser.add_argument("output", help="Path for the output .tif file")

    args = parser.parse_args()

    # Execute the conversion
    convert_anunc_to_tiff(args.input, args.output)

if __name__ == "__main__":
    main()
     

